export const group_tabs = [
  {
    id: 1,
    name: "Darsliklar",
    url: "",
    component: "PageGroupLessonsMain",
    role: [],
  },
  {
    id: 2,
    name: "Chat",
    url: "chat",
    component: "PageGroupChatMain",
    role: [],
  },
  {
    id: 3,
    name: "Reyting",
    url: "reyting",
    component: "PageGroupReytingMain",
    role: [],
  },
  {
    id: 4,
    name: "Kalendar",
    url: "calendar",
    component: "PageGroupCalendarMain",
    role: [],
  },
  {
    id: 5,
    name: "A'zolar",
    url: "members",
    component: "PageGroupMembersMain",
    role: [],
  },
  {
    id: 6,
    name: "Davomat",
    url: "activity",
    component: "PageGroupActivityMain",
    role: [],
  },
  {
    id: 7,
    name: "Yangiliklar",
    url: "news",
    component: "PageGroupNewsMain",
    role: [],
  },
   {
    id: 8,
    name: "Haqida",
    url: "about",
    component: "PageGroupAboutMain",
    role: [],
  },
  {
    id: 9,
    name: "Sozlamalar",
    url: "settings",
    component: "PageGroupSettingsMain",
    role: [],
  },
];
