export const group_tabs = [
  {
    id: 1,
    name: "Darsliklar",
    url: "?",
    component: "PageGroupLessonsMain",
    role: [],
  },
  {
    id: 2,
    name: "Chat",
    url: "?page=chat",
    component: "PageGroupChatMain",
    role: [],
  },
  {
    id: 3,
    name: "Reyting",
    url: "?page=reyting",
    component: "PageGroupReytingMain",
    role: [],
  },
  {
    id: 4,
    name: "Kalendar",
    url: "?page=calendar",
    component: "PageGroupCalendarMain",
    role: [],
  },
  {
    id: 5,
    name: "A'zolar",
    url: "?page=members",
    component: "PageGroupMembersMain",
    role: [],
  },
  {
    id: 6,
    name: "Yangiliklar",
    url: "?page=news",
    component: "PageGroupNewsMain",
    role: [],
  },
  {
    id: 7,
    name: "Sozlamalar",
    url: "?page=settings",
    component: "InfiniteScroll",
    role: [],
  },
];
